# Generated by Django 4.2.16 on 2024-10-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='journal_entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
