# Generated by Django 4.2.16 on 2024-10-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_chessgame_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='move_count',
            field=models.IntegerField(default=0),
        ),
    ]
