# Generated by Django 4.2.16 on 2024-12-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_chessgame_move_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='player1_move_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='player2_move_count',
            field=models.IntegerField(default=0),
        ),
    ]
